require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Naming/FileName:
  Exclude:
    - lib/twitch-api.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
