require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Naming/FileName:
  Exclude:
    - lib/twitch-api.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
